# Generated by Django 4.0.2 on 2022-03-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contribute',
        ),
    ]
